# pastyAware 2
# https://github.com/evanwill/pastyAware

# Site settings
title: Pasty Awareness Week
description: "National Pasty Awareness Week seeks to bring attention to this little known cultural food treasure to improve the lives of all Americans."
keywords: "pasty, national holiday, food culture"
featured-image: "/assets/images/pastyProfile.jpg"

# author settings
author: evan will
pub_year: 2016
github_username: evanwill

# github repository
repo: "https://github.com/evanwill/pastyAware"

# site urls
url: https://evanwill.github.io
baseurl: /pastyAware

# use JEKYLL_ENV=production on build command
google_analytics: UA-74844011-1

# Build settings
markdown: kramdown
